"""empty message

Revision ID: 29f8da16c8b7
Revises: 320d0c17f2ed
Create Date: 2020-02-28 16:52:46.025205

"""

# revision identifiers, used by Alembic.
revision = '29f8da16c8b7'
down_revision = '320d0c17f2ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
