"""empty message

Revision ID: 2db79e87e9c8
Revises: cfb6eae282cd
Create Date: 2020-02-28 17:36:32.335840

"""

# revision identifiers, used by Alembic.
revision = '2db79e87e9c8'
down_revision = 'cfb6eae282cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
