"""empty message

Revision ID: 320d0c17f2ed
Revises: 1161a23583f9
Create Date: 2020-02-28 16:23:53.315066

"""

# revision identifiers, used by Alembic.
revision = '320d0c17f2ed'
down_revision = '1161a23583f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
