"""empty message

Revision ID: 7fda8df185fd
Revises: 2cd7a920ec59
Create Date: 2020-02-29 13:21:22.602359

"""

# revision identifiers, used by Alembic.
revision = '7fda8df185fd'
down_revision = '2cd7a920ec59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
