"""empty message

Revision ID: cfb6eae282cd
Revises: 29f8da16c8b7
Create Date: 2020-02-28 17:33:38.874860

"""

# revision identifiers, used by Alembic.
revision = 'cfb6eae282cd'
down_revision = '29f8da16c8b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
